#!/bin/bash

set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/plugin.bash
. "${DIR}/../lib/plugin.bash"

DRY_RUN="${DRY_RUN:-}"

REPOSITORY_URL_OPTION=$(plugin_read_config REPOSITORY_URL "${BUILDKITE_REPO:-}")
SSH_SECRET_KEY_NAME_OPTION=$(plugin_read_config SSH_SECRET_KEY_NAME "GIT_SSH_CHECKOUT_PLUGIN_SSH_KEY")
CHECKOUT_PATH_OPTION=$(plugin_read_config CHECKOUT_PATH "${BUILDKITE_BUILD_CHECKOUT_PATH:-.}")

echo "Running SSH Checkout plugin with options:"
echo " - repository-url: ${REPOSITORY_URL_OPTION}"
echo " - ssh-secret-key-name: ${SSH_SECRET_KEY_NAME_OPTION}"
echo " - checkout-path: ${CHECKOUT_PATH_OPTION}"

if [ "${DRY_RUN}" != "true" ]; then
  KEY_DIRECTORY=$(mktemp -d "$(cd .. && pwd)/git_ssh_checkout_plugin_ssh_key.XXXXXX")
  KEY_NAME="${KEY_DIRECTORY}/id"

  # Populate the key file from the secret value
  buildkite-agent secret get "${SSH_SECRET_KEY_NAME_OPTION}" | tr -d '\015' > "${KEY_NAME}"
  chmod 0400 "${KEY_NAME}"
  plugin_configure_ssh_command "${KEY_NAME}"

  # Clone the repository
  git clone "${REPOSITORY_URL_OPTION}" "${CHECKOUT_PATH_OPTION}"

  cd "${CHECKOUT_PATH_OPTION}"
  git config core.sshCommand "${GIT_SSH_COMMAND}"

  # Clean up the clone
  git clean -ffxdq

  # Checkout the branch
  if [ "${BUILDKITE_BRANCH:-}" != "" ]; then
    # Fetch the branch
    git fetch -v --prune -- origin "refs/heads/${BUILDKITE_BRANCH}"
  fi

  # Checkout the correct ref to continue the build
  if [ "${BUILDKITE_COMMIT:-}" = "HEAD" ] || [ "${BUILDKITE_COMMIT}" = "" ]; then
    git checkout -f "origin/${BUILDKITE_BRANCH}"
  else
    git checkout -f "${BUILDKITE_COMMIT}"
  fi
fi
